# Generated by Django 3.1.1 on 2020-09-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=50)),
                ('system', models.CharField(max_length=50)),
                ('task', models.CharField(max_length=50)),
                ('procedure', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=500)),
                ('owner', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True)),
            ],
        ),
    ]
