# Generated by Django 3.1.1 on 2020-10-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_auto_20201003_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
